require "user.config.plugins.dressing"
require "user.config.plugins.VimVisualMulti"
require "user.config.plugins.LspSaga"
require "user.config.plugins.nvim_lightbulb"
require "user.config.plugins.wilder"
-- require "user.config.plugins.bufferlinekill"
require "user.config.plugins.MiniFiles"
require "user.config.plugins.Oil"
require "user.config.plugins.interestingwords"
require "user.config.plugins.winshift"
require "user.config.plugins.BookMarks"
require "user.config.plugins.OrgMode"
require "user.config.plugins.mkdnflow"
require "user.config.plugins.headline"
require "user.config.plugins.MarkdownNvim"
-- require "user.config.plugins.MarksmanLspEnhance"
require "user.config.plugins.fold"
require "user.config.plugins.Narrowing"
require "user.config.plugins.scratch"

require "user.config.plugins.text"
-- .env file will load by dotenv

require "user.config.plugins.env_template"
require "user.config.plugins.dadbod"
require "user.config.plugins.floatwindow"
require "user.config.plugins.ipython"
require "user.config.plugins.bioinformatics"
